config/routes.rb
Rails.application.routes.draw do
  root 'github/repositories#index'

  namespace :github do
    resources :repositories, only: [:index, :show, :new, :create, :destroy] do
      member do
        post :fetch
      end
    end
  end
end

app/models/api/github.rb
class Api::Github
  class << self
    def repos_issues(owner:, repo:, page:, per_page: nil)
      params = { page: page }
      params[:per_page] = per_page if per_page

      connection.get("/repos/#{owner}/#{repo}/issues", params)
    end

    private

      def connection
        @connection ||= Faraday.new(url: "https://api.github.com") do |builder|
          builder.use :http_cache, store: Rails.cache, serializer: Marshal, logger: Rails.logger
          builder.response :logger, Rails.logger
          builder.adapter Faraday.default_adapter
        end
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github.rb
module Github
  def self.table_name_prefix
    'github_'
  end
end

app/models/github/issue.rb
class Github::Issue < ApplicationRecord
  belongs_to :repository, class_name: 'Github::Repository', foreign_key: :github_repository_id

  FETCH_COUNT = 5
end

app/models/github/repository.rb
class Github::Repository < ApplicationRecord
  has_many :issues, class_name: 'Github::Issue', foreign_key: :github_repository_id, dependent: :destroy

  validates :owner, presence: true
  validates :repo, presence: true
  validates_uniqueness_of :owner, scope: [:repo]

  def display_name
    @display_name ||= self.class.display_name(owner, repo)
  end

  def html_url
    @html_url ||= self.class.html_url(owner, repo)
  end

  def refresh_issues
    begin
      response = Api::Github.repos_issues(owner: owner, repo: repo, page: 1, per_page: Github::Issue::FETCH_COUNT)
      return false unless response.success?

      res_issues = JSON.parse(response.env.body)
      hash_issues = GithubIssue.new(res_issues).to_hash

      # NOTE: 最大件数を考えて bulk でないことを許容する
      self.transaction do
        issues.each(&:destroy!)
        issues.create!(hash_issues)
      end

      return true
    rescue => e
      logger.error e.class
      logger.error e.message
      logger.error e.backtrace.join("\n")
    end

    false
  end

  class << self
    def display_name(owner, repo)
      "#{owner} / #{repo}"
    end

    def html_url(owner, repo)
      "https://github.com/#{owner}/#{repo}/"
    end
  end
end

app/models/github_issue.rb
require "csv"

class GithubIssue
  def initialize(issues)
    @issues = issues.map(&:with_indifferent_access)
  end

  def to_csv
    CSV.generate do |csv|
      @issues.each do |issue|
        hash = convert_hash(issue)
        csv.add_row([hash[:title], hash[:body], hash[:html_url]])
      end
    end
  end

  def to_hash
    @issues.map do |issue|
      convert_hash(issue)
    end
  end

  private

    def convert_hash(issue)
      {
        title: issue[:title].try(:slice, 0, 30),
        body: issue[:body].try(:slice, 0, 50),
        html_url: issue[:html_url],
      }
    end
end

app/models/rails_issues.rb
class RailsIssues
  class << self
    def puts_csv(page:)
      response = Api::Github.repos_issues(owner: "rails", repo: "rails", page: page)

      if response.success?
        puts_success(response)
      else
        puts_error(response)
      end
    end

    private

      def puts_success(response)
        issues = JSON.parse(response.env.body)
        csv = GithubIssue.new(issues).to_csv

        puts csv
      end

      def puts_error(response)
        error_info = {
          "url": response.env.url.to_s,
          "status": response.status,
          "headers": response.env.response_headers,
          "body": response.body,
        }

        puts "[Error]"
        puts error_info.to_yaml
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github/repositories_controller.rb
class Github::RepositoriesController < ApplicationController
  before_action :set_repository, only: [:destroy, :fetch]
  before_action :set_repository_with_issues, only: [:show]

  # GET /github/repositories
  def index
    @repositories = Github::Repository.all
  end

  # GET /github/repositories/1
  def show
  end

  # GET /github/repositories/new
  def new
    @repository = Github::Repository.new
  end

  # POST /github/repositories
  def create
    @repository = Github::Repository.new(repository_params)

    if @repository.save
      redirect_to root_url, notice: t('.success')
    else
      render :new
    end
  end

  # DELETE /github/repositories/1
  def destroy
    if @repository.destroy
      redirect_to root_url, notice: t('.success')
    else
      redirect_to root_url, alert: @repository.errors.full_messages[0]
    end
  end

  # POST /github/repositories/1/fetch
  def fetch
    if @repository.refresh_issues
      redirect_to @repository, notice: t('.success')
    else
      redirect_to @repository, alert: t('.failure')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Github::Repository.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_repository_with_issues
      @repository = Github::Repository.eager_load(:issues).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def repository_params
      params.require(:github_repository).permit(:owner, :repo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def empty_message
    tag.div(class: 'message is-warning') do
      tag.div(class: 'message-body') { 'There is no data to display.' }
    end
  end
end

app/views/application/_notice.html.slim
ruby:
  notification_class = { notice: 'is-info', alert: 'is-danger' }
  notification_types = notification_class.keys

- notification_types.each do |type|
  - if flash[type]
    = tag.div(class: ['notification', notification_class[type]])
      button.delete
      p = flash[type]

- if notification_types.any? {|type| flash[type] }
  javascript:
    document.addEventListener('turbolinks:load', function() {
      var elements = document.querySelectorAll('.notification > .delete')
      for (var element of elements) {
        element.addEventListener('click', function(e) {
          e.target.parentNode.classList.add('is-hidden')
        })
      }
    })

app/views/github/repositories/_form.html.slim
= form_for repository do |f|
  .field
    - if repository.errors.any?
      article.message.is-danger#error_explanation
        .message-body
          .conent
            strong = t('.error_message', count: repository.errors.count)
          ul
            - repository.errors.full_messages.each do |message|
              li = message

  .field
    label.label = Github::Repository.human_attribute_name(:display_name)
    .control
      .field.has-addons
        .control
          = f.text_field :owner, placeholder: Github::Repository.human_attribute_name(:owner), class: 'input'
        .control
          span.button.is-static = '/'
        .control
          = f.text_field :repo, placeholder: Github::Repository.human_attribute_name(:repo), class: 'input'
    p.help = t('.owner_repo_help')

  hr

  .field
    = f.submit class: 'button is-primary'

app/views/github/repositories/index.html.slim
section.content
  h1.title = t('.title')
  p.content = t('.note')

  - if @repositories.empty?
    = empty_message
  - else
    table.table.is-striped.is-hoverable
      thead
        tr
          th = Github::Repository.human_attribute_name(:display_name)
          th
      tbody
        - @repositories.each do |repository|
          tr
            td = link_to repository.display_name, repository
            td.has-text-right = link_to t('.delete'), repository, data: { confirm: t('delete_confirm') }, method: :delete, class: 'has-text-danger'

hr

section.content
  = link_to t('.new'), new_github_repository_path, class: 'button is-primary'

app/views/github/repositories/new.html.slim
section.content
  = link_to t('page_back'), root_path

section.content
  h1.title = t('.title')
  = render 'form', repository: @repository

app/views/github/repositories/show.html.slim
section.content
  = link_to t('page_back'), root_path

section.content
  h1.title
    = link_to @repository.display_name, @repository.html_url, target: '_blank'

section.content
  section.content
    - if @repository.issues.empty?
      = empty_message
    - @repository.issues.each do |issue|
      section.box
        h2.subtitle = link_to issue.title, issue.html_url, target: '_blank'
        .content = simple_format(h(issue.body), {}, wrapper_tag: 'div')
  section.content
    p = t('.fetch_note', count: Github::Issue::FETCH_COUNT)
    = link_to t('.fetch'), fetch_github_repository_path, method: :post, class: 'button is-primary'

hr

section.content
  h2.subtitle = t('.danger_zone.title')
  .content
    strong = t('.danger_zone.delete.title')
    p = t('.danger_zone.delete.note')
    = link_to t('.danger_zone.delete.delete'), @repository, data: { confirm: t('delete_confirm') }, method: :delete, class: 'button is-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('title')
    meta name="viewport" content="width=device-width, initial-scale=1"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.is-primary aria-label="main navigation"
      .navbar-brand
        = link_to t('title'), root_path, class: 'navbar-item has-text-weight-bold'
    section.section
      .container
        = render 'notice'
        = yield
    footer.footer
      .content.has-text-centered
        - owner = 'hayato-yamashita'
        - repo = 'github-issue-atsume'
        = link_to Github::Repository.html_url(owner, repo), target: '_blank'
          = Github::Repository.display_name(owner, repo)